#spring:
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#  servlet:
#    multipart:
#      max-request-size: 50MB
#      max-file-size: 50MB
#  datasource:
#    username: root
#    password:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://120.78.157.142:3306/firstbase?useSSL=true
##    druid:
##      db-type: com.alibaba.druid.pool.DruidDataSource
##      driver-class-name: com.mysql.jdbc.Driver
##      username: root
##      password: asdasd123123
##      url: jdbc:mysql://localhost:3306/firstbase?useSSL=true
##      initial-size: 10
##      max-active: 30
##      min-idle: 10
##      max-wait: 60000
##      #打开PSCache，并指定大小
##      max-pool-prepared-statement-per-connection-size: 20
##      pool-prepared-statements: true
##      #是否在连接后检测其可用性
##      test-on-borrow: false
##      #是否在连接空闲一段时间后检测其可用性
##      test-while-idle: true
##      #是否在连接放回连接池后检测其可用性
##      spring.datasource.druid.test-on-return=false
##    type: com.alibaba.druid.pool.DruidDataSource
#server:
#  port: 8080